# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
log_u_pdf_check <- function(x, bj, d1, beta, sigma2, Ci_tp) {
    .Call('_hmmgibbs_log_u_pdf_check', PACKAGE = 'hmmgibbs', x, bj, d1, beta, sigma2, Ci_tp)
}

#' @export
sample_u_cpp_check <- function(bj, d1, beta, sigma2, C_mat, nsamp, ii) {
    .Call('_hmmgibbs_sample_u_cpp_check', PACKAGE = 'hmmgibbs', bj, d1, beta, sigma2, C_mat, nsamp, ii)
}

sample_u_cpp <- function(bj, d1, beta, sigma2, C_mat) {
    .Call('_hmmgibbs_sample_u_cpp', PACKAGE = 'hmmgibbs', bj, d1, beta, sigma2, C_mat)
}

